site_name: 22/7 WiKi
site_url: https://227wiki.eu.org
nav:
  - 首页: index.md
  - 简介:
    - 关于22/7: intro/about.md
    - 关于22/7 WiKi: intro/about-wiki.md
    - 参与修订: intro/commit.md
    - Markdown特别用法: intro/markdown.md
    - 版权协议: license.md
  - 成员:
    - 现役成员:
      - 西條和: member/nagomi.md
      - 天城莎莉: member/sally.md
      - 凉花萌: member/moe.md
      - 河濑诗: member/uta.md
      - 相川奈央: member/nao.md
      - 麻丘真央: member/mao.md
      - 清井美那: member/mina.md
      - 椎名桜月: member/satsuki.md
      - 四条月: member/luna.md
      - 月城咲舞: member/emma.md
      - 望月りの: member/rino.md
    - 毕业成员:
      - 雨夜音: member/oto.md
      - 白泽加奈惠: member/kanae.md
      - 宫濑玲奈(佐仓初): member/reina.md
      - 海乃琉璃(吉宫瑠织): member/ruri.md
      - 仓冈水巴(仓丸莉子): member/mizuha.md
      - 武田爱奈: member/aina.md
      - 高辻丽(日永丽): member/urara.md
      - 帆风千春(千春): member/chiharu.md
      - 花川芽衣(浅仓唯): member/mei.md
  - Live:
    - 索引: live/index.md
    - Anniversary Live 2020: live/Anniv20.md
    - "11": live/11.md
    - Mission Paradise: live/mp.md
  - 歌曲:
    - 索引: songs/index.md
    - 单曲:
        
        - 不曾存在的我: 
          - 简介: songs/single/1st/index.md
          - 歌曲:
            - 不曾存在的我: songs/single/1st/song-1.md
            - 地下铁抵抗主义: songs/single/1st/song-2.md
            - 11人聚集的理由: songs/single/1st/song-3.md
        - 散发出了香波的气息: 
          - 简介: songs/single/2nd/index.md
          - 歌曲:
            - 散发出了香波的气息: songs/single/2nd/song-1.md
            - 人格崩坏: songs/single/2nd/song-2.md
            - 温柔的记忆: songs/single/2nd/song-3.md
            - 只能呐喊的青春: songs/single/2nd/song-4.md
            - 循环巴士: songs/single/2nd/song-5.md
        - 理解者: 
          - 简介: songs/single/3rd/index.md
          - 歌曲:
            - 理解者: songs/single/3rd/song-1.md
            - 绝望之花: songs/single/3rd/song-2.md
            - 韦驮天娘: songs/single/3rd/song-3.md
            - 不确定的青春: songs/single/3rd/song-4.md
            - 因为还有未来: songs/single/3rd/song-5.md
        - 什么都无法为你做到: 
          - 简介: songs/single/4th/index.md
          - 歌曲:
            - 什么都无法为你做到: songs/single/4th/song-1.md
            - 你是月亮: songs/single/4th/song-2.md
            - 蜻蜓的心情: songs/single/4th/song-3.md
            - 浪漫积木: songs/single/4th/song-4.md
            - 谎言之雨: songs/single/4th/song-5.md 
        - 太难了: 
          - 简介: songs/single/5th/index.md
          - 歌曲:
            - 太难了: songs/single/5th/song-1.md
            - 天空的祖母绿: songs/single/5th/song-2.md
            - 我们的环境: songs/single/5th/song-3.md
            - 洗脚吧!: songs/single/5th/song-4.md
            - 愿望的视线: songs/single/5th/song-5.md
        - 风在吹吗?: 
          - 简介: songs/single/6th/index.md
          - 歌曲:
            - 风在吹吗?: songs/single/6th/song-1.md
            - 马尾别转身: songs/single/6th/song-2.md
            - 半炒饭: songs/single/6th/song-3.md
            - 纹身·爱: songs/single/6th/song-4.md
            - 冰激凌掉地上: songs/single/6th/song-5.md
        - 若是我的所有之物: 
          - 简介: songs/single/7th/index.md
          - 歌曲:
            - 若是我的所有之物: songs/single/7th/song-1.md
            - タチツテト力量: songs/single/7th/song-2.md
            - 说喜欢是骗人的: songs/single/7th/song-3.md
            - 猕猴桃主张(白组): songs/single/7th/song-4.md
            - 雷鸣的Delay(红组): songs/single/7th/song-5.md
        - 觉醒: 
          - 简介: songs/single/8th/index.md
          - 歌曲:
            - 觉醒: songs/single/8th/song-1.md
            - Just here and now: songs/single/8th/song-2.md
            - 不知何时的日出: songs/single/8th/song-3.md
            - 今年的 第一场雪(红组): songs/single/8th/song-4.md
            - 摘下耳机!(白组): songs/single/8th/song-5.md
        - 曇り空の向こうは晴れている:
          - 简介: songs/single/9th/index.md
          - 歌曲:
            - 曇り空の向こうは晴れている: songs/single/9th/song-1.md
            - 打ち上げ花火の拒否権: songs/single/9th/song-2.md
            - 君は誰だ？: songs/single/9th/song-3.md
            - カントリーガール: songs/single/9th/song-4.md
            - 読みかけの漫画: songs/single/9th/song-5.md
    - 专辑:
      - 名为11的永远的素数: 
        - 简介: songs/album/1st/index-disc.md
        - Disc1:
          - 不曾存在的我: songs/single/1st/song-1.md
          - 散发出了香波的气息: songs/single/2nd/song-1.md
          - 理解者: songs/single/3rd/song-1.md
          - 什么都无法为你做到: songs/single/4th/song-1.md
          - 太难了: songs/single/5th/song-1.md
          - 风在吹吗?: songs/single/6th/song-1.md
          - 若是我的所有之物: songs/single/7th/song-1.md
          - 风信子: songs/album/1st/song-1.md
          - 试着在空中飞翔吧: songs/album/1st/song-2.md
          - 11人聚集的理由: songs/single/1st/song-3.md
        - Disc2(角色歌):
          - 简介: songs/album/1st/index-disc2.md 
        - Disc3(组合歌):
          - 半炒饭: songs/single/6th/song-3.md
          - To go请多关照: songs/album/1st/song-3.md
          - 纹身·爱: songs/single/6th/song-4.md
          - 交换条件: songs/album/1st/song-4.md
          - 冰激凌掉地上: songs/single/6th/song-5.md
          - 喜欢上你是我的自由: songs/album/1st/song-5.md
          - 猕猴桃主张(白组): songs/single/7th/song-4.md
          - 雷鸣的Delay(红组): songs/single/7th/song-5.md
        - BD:
          - 简介: songs/album/1st/index-bd.md
      - 旅人算: 
        - 简介: songs/album/2nd/index.md
  - 动画:
    - 简介: anime/index.md
  
  - 计算中:
    - 简介: keisanchu/index.md

  - 检算中:
    - 简介: kensanchu/index.md
  
  - 广播:
    - 除不尽广播:
      - 简介: radio/warikirenai/index.md
    - ナナニジ RADIO:
      - 简介: radio/fcradio/index.md

  - 个人节目/直播:
    - 索引: personal-bangumi/index.md

  - 生放送/节目:
    - 索引: bangumi/index.md

  - 游戏: 
    - 简介: game/index.md
    - 卡面: game/card.md

  - 博客: https://blog.227wiki.eu.org
    
  - 直播: watch.md

theme:
  name: material
  palette:
    primary: white
    accent: light blue
  language: zh
  logo: assets/logo.svg
  favicon: assets/favicon.png
  custom_dir: overrides
  font: 
    text: YSHaoShenTi
    code: qingyuan
  
  features:
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github-alt

repo_url: https://github.com/227WiKi/227WiKi
repo_name: 227WiKi/227WiKi
edit_uri: edit/master/docs/

plugins:
  - search:
      lang: 
        - ja
        - en
      separator: '[\s\-\.]+'
  - git-committers:
      repository: 227WiKi/227WiKi
      branch: master
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: true
      caption_position: bottom
extra_css:
  - '_static/css/extra.css'
  - '_static/css/glightbox.min.css'
  - stylesheets/extra.css
  - https://nananiji.zzzhxxx.top/css/jquery.fancybox.min.css
  - https://nananiji.zzzhxxx.top/css/APlayer.min.css
extra_javascript:
  - '_static/js/glightbox.min.js'
  - '_static/js/glightbox.js'
  - https://nananiji.zzzhxxx.top/js/jquery.min.js
  - https://nananiji.zzzhxxx.top/js/jquery.fancybox.min.js
  - https://nananiji.zzzhxxx.top/js/DPlayer.min.js
  - https://nananiji.zzzhxxx.top/js/md5.js
  - https://nananiji.zzzhxxx.top/js/APlayer.min.js
  - https://nananiji.zzzhxxx.top/js/Meting.min.js
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FiberBell
      name: zzzhxxx on Twitter
    - icon: pack/bili
      link: https://space.bilibili.com/40127239
      name: zzzhxxx on BilBili
    - icon: pack/227
      link: https://nanabunnonijyuuni.com/
      name: 22/7 Official Website
    - icon: fontawesome/solid/paper-plane
      link: mailto:<feedback@zzzhxxx.top>
  analytics:
    provider: google
    property: G-WR7E2E5BRB

copyright: Copyright &copy; 2021 - 2023 22/7 WiKi

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


