site_name: 22/7 WiKi
nav:
  - 简介:
    - Getting start: index.md
    - 关于: intro/about.md
    - 参与修订: intro/commit.md
  - 成员:
    - 西條和: member/nagomi.md
theme:
  name: material
  palette:
    primary: white
  language: zh
  logo: assets/logo.svg
  custom_dir: overrides
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
  icon:
    repo: fontawesome/brands/github-alt

repo_url: https://github.com/zzzhxxx/227WiKi
repo_name: zzzhxxx/227WiKi
edit_uri: edit/master/docs/

plugins:
  - search

extra_css:
  - '_static/css/extra.css?v=13'
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FiberBell
    - icon: pack/bili
      link: https://space.bilibili.com/40127239
    - icon: pack/227
      link: https://nanabunnonijyuuni.com/

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - fancyboxmd:
      preview_width: 100%
  - attr_list


