site_name: 22/7 WiKi
site_url: https://227WiKi.github.io/227WiKi/
nav:
  - 首页: index.md
  - 简介:
    - 关于: intro/about.md
    - 参与修订: intro/commit.md
  - 成员:
    - 现役成员:
      - 西條和: member/nagomi.md
      - 天城莎莉: member/sally.md
      - 凉花萌: member/moe.md
      - 宫濑玲奈: member/reina.md
      - 白泽加奈惠: member/kanae.md
      - 河濑诗: member/uta.md
      - 相川奈央: member/nao.md
      - 麻丘真央: member/mao.md
      - 雨夜音: member/oto.md
      - 清井美那: member/mina.md
      - 椎名桜月: member/satsuki.md
      - 四条月: member/luna.md
      - 月城咲舞: member/emma.md
      - 望月りの: member/rino.md
    - 毕业成员:
      - 海乃琉璃: member/ruri.md
      - 仓冈水巴(仓丸莉子): member/mizuha.md
      - 武田爱奈: member/aina.md
      - 高辻丽: member/urara.md
      - 帆风千春(千春): member/chiharu.md
      - 花川芽衣(浅仓唯): member/mei.md
  - Live:
    - 索引: live/index.md
    - Anniversary Live 2020: live/Anniv20.md
    - "11": live/11.md
    - Mission Paradise: live/mp.md
  - 歌曲:
    - 索引: songs/index.md
    - 单曲:
        
        - 不曾存在的我: 
          - 简介: songs/single/1st/index.md
          - 歌曲:
            - 不曾存在的我: songs/single/1st/song-1.md
            - 地下铁抵抗主义: songs/single/1st/song-2.md
            - 11人聚集的理由: songs/single/1st/song-3.md
  - 动画:
    - 简介: anime/index.md
  
  - 计算中:
    - 简介: keisanchu/index.md

  - 检算中:
    - 简介: kensanchu/index.md
  
  - 除不尽广播:
    - 简介: radio/index.md

  - 个人节目/直播:
    - 索引: personal-bangumi/index.md

  - 生放送/节目:
    - 索引: bangumi/index.md

  - 游戏: 
    - 简介: game/index.md
    - 卡面: game/card.md

  - 博客:
    - 列表: blog-content.md
    - 索引: tags.md
theme:
  name: material
  palette:
    primary: white
    accent: light blue
  language: zh
  logo: assets/logo.svg
  favicon: assets/favicon.png
  custom_dir: overrides
  font:
    text: Fira Sans
    code: Fira Mono
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
  icon:
    repo: fontawesome/brands/github-alt

repo_url: https://github.com/227WiKi/227WiKi
repo_name: 227WiKi/227WiKi
edit_uri: edit/master/docs/

plugins:
  - search
  - git-committers:
      repository: 227WiKi/227WiKi
      branch: master
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - blogging:
      theme:
        name: card
        options: # Optional
          # `true` if display the button as plain text
          # `false` or not present if display as rectangle button
          - plain_button: true
          # Replacement for 'Continue Reading'
          - label: Read
      dirs: # The directories to be included
        - blog
      features:
        tags: 
          index_page: tags.md
          insert: bottom
      sort:
        from: new       
        by: revision
      template: overrides/custom-blog.html
extra_css:
  - '_static/css/extra.css?v=13'
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
  - https://unpkg.com/gitalk/dist/gitalk.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
  - https://cdn.jsdelivr.net/npm/dplayer@1.26.0/dist/DPlayer.min.js
  - https://cdn.jsdelivr.net/gh/zzzhxxx/227WiKi@1.2/docs/_static/js/md5.js
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FiberBell
    - icon: pack/bili
      link: https://space.bilibili.com/40127239
    - icon: pack/227
      link: https://nanabunnonijyuuni.com/

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fancyboxmd:
      preview_width: 100%


